Adding HELP to print all usages declared in the scripts
(and DBG to show usages while executing)

roadmap for 1.0 lacks unit test and better docs.

Functionnally I am done.

diff --git a/secrets b/secrets
--- a/secrets
+++ b/secrets
@@ -6,7 +6,7 @@ GR=${GR-'\e[92m'}
 RD=${RD-'\e[91m'}
 HL=${HL-'\e[1m'}
 
-function die { EN=$1; shift; echo -e "ERR::${RD}$@${RZ}"; exit "$EN"; }
+function die { EN=$1; [[ $EN != "10" ]] && ST="Error:"; shift; echo -e "$ST${RD}$@${RZ}"; exit "$EN"; }
 function clean { unset CAGE; unset CAGE_C; unset STASH; unset RD; unset GR; unset HL; }
 # don't kill me pliz
 function usage { curl https://raw.githubusercontent.com/jul/secrets/main/README.md | ${PAGER-less} ; die 0 "AIDE"; }
@@ -60,27 +60,32 @@ fi
 [ -f "$FILE" ] || die 2 "no such secret"
 CAGE=${CAGE-$( basename $FILE )}
 source "$FILE" || \
-    ( die 5 "execution of ${FILE} died unexpectedly check syntax" )
+    ( [[ $? != "10" ]] &&  die 5 "${FILE} died with status $?" )
+if [ ! -z "${HELP-""}" ] || [ ! -z "${DBG-""}" ]; then
+    USAGE=${USAGE-"${RD}no usage found${RZ}"};
+	MSG="${HL}USAGE $CAGE\\n${RZ}\\n$USAGE\\n";
+	[ ! -z "${HELP}" ] && die 10 "$MSG" || echo -e "$MSG";
+fi
 # if a ressource cleaning function is declared with the name *finally*
 # in the secret execute it at exit time
-declare -f finally > /dev/null && trap finally EXIT
+okko() {
+	ST="cleanup action detected for ${CAGE}${RZ}.\\nStatus:";
+	finally && echo -e "${ST}${GR}OK${RZ}" || echo -e "${ST}${RD}KO${RZ}" ;
+}
+declare -f finally > /dev/null && trap okko  EXIT
 if [ ! -z "$CAGE_C" ]; then
     CAGE_C="${CAGE_C}->${RD}${CAGE}"
 else
     CAGE_C="${RD}#SEC:${CAGE}"
 fi
-
-[ -z ${HELP-""} ] || \
-    ( [ -z "$USAGE" ] && echo -e "${RD}no usage found${RZ}" || die 10 "USAGE:${RZ}\\n$USAGE" )
-
-shift
 export CAGE_C
+shift
 if [ -z "$1" ]; then
 # sane idented use as a "python activate"
     PRMPT="${HL}${CAGE_C}${RZ}:"
     ( PS1="${PRMPT}$PS1" bash --norc -i)
 else
 # shell escaping hell, try to avoid
-    eval "$@"
+    [ -z "$HELP" ] && eval "$@"
 fi
 
